os: linux
dist: xenial
language: python
python:
    - "3.7.7"
before_install:
    - sudo apt-get -y install graphviz
    - sudo bash ci/linux.bash
install:
    - pip install pipenv
    - (cd pipenvconf/oo && PIPENV_IGNORE_VIRTUALENVS=1 pipenv install -d)
    - (cd pipenvconf/pure && PIPENV_IGNORE_VIRTUALENVS=1 pipenv install -d)
script:
    - . ./env.source
    - (cd pipenvconf/oo && ODBINFO_NO_BROWSE=1 PIPENV_IGNORE_VIRTUALENVS=1 pipenv run make -C ../..   travis)
    - (cd pipenvconf/pure && ODBINFO_NO_BROWSE=1 PIPENV_IGNORE_VIRTUALENVS=1 pipenv run make -C ../.. clean coverage)
    - (cd pipenvconf/pure && ODBINFO_NO_BROWSE=1 PIPENV_IGNORE_VIRTUALENVS=1 pipenv run make -C ../.. metric mypy)
