os: linux
dist: xenial
language: python
python:
    - "3.7"
before_install:
    - sudo apt-get -y install graphviz ruby-full build-essential zlib1g-dev
    - sudo bash ci/linux.bash
install:
    - pip install pipenv
    - PIPENV_IGNORE_VIRTUALENVS=1 pipenv install -d
    - export GEM_HOME=~/gems
    - export PATH=$PATH:~/gems/bin
    - gem install jekyll bundler
script:
    - PIPENV_IGNORE_VIRTUALENVS=1 pipenv run make all
