os: linux
dist: xenial
language: python
python:
    - "3.7.7"
before_install:
    - sudo bash/install-development-runtime.sh
install:
    - pip install pipenv
    - bash/install-venvs.sh
script:
    - bash/build.sh
